# Generated by Django 5.1.3 on 2024-11-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(verbose_name='Número'),
        ),
    ]
