# Generated by Django 5.1.3 on 2024-11-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Fecha de entrada')),
                ('check_out', models.DateField(verbose_name='Fecha de salida')),
                ('guest_name', models.CharField(max_length=100, verbose_name='Nombre del huésped')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='Email del huésped')),
                ('guest_phone', models.CharField(max_length=20, verbose_name='Teléfono del huésped')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('checked_in', 'Check-in'), ('checked_out', 'Check-out'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-check_in'],
            },
        ),
    ]
