# Generated by Django 5.1.3 on 2024-11-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pre_reserve_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiración de pre-reserva'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pre_reserved', 'Pre-reservada'), ('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('checked_in', 'Check-in'), ('checked_out', 'Check-out'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
