# Generated by Django 5.1.3 on 2024-11-26 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_pre_reserve_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de entrada'),
        ),
    ]
